Repository UCF/PostMaster, pull requests merged in 2021-08, with the labels that each got.

#121 Importer optimizations
  manager/management/commands/import-emails.py
  manager/utils.py
Labels: bug

#123 Dependencies, package upgrades
  gulpfile.js
  package-lock.json
  package.json
  requirements.txt
  setup.py
  static/css/style.min.css
  static/js/script.min.js
  static/webfonts/fontawesome/fa-brands-400.eot
  static/webfonts/fontawesome/fa-brands-400.svg
  static/webfonts/fontawesome/fa-brands-400.ttf
  static/webfonts/fontawesome/fa-brands-400.woff
  static/webfonts/fontawesome/fa-brands-400.woff2
  static/webfonts/fontawesome/fa-regular-400.eot
  static/webfonts/fontawesome/fa-regular-400.svg
  static/webfonts/fontawesome/fa-regular-400.ttf
  static/webfonts/fontawesome/fa-regular-400.woff
  static/webfonts/fontawesome/fa-regular-400.woff2
  static/webfonts/fontawesome/fa-solid-900.eot
  static/webfonts/fontawesome/fa-solid-900.svg
  static/webfonts/fontawesome/fa-solid-900.ttf
  static/webfonts/fontawesome/fa-solid-900.woff
  static/webfonts/fontawesome/fa-solid-900.woff2
Labels: dependencies

#124 Email instance open rate adjustments
  manager/models.py
  manager/views.py
Labels: enhancement

#128 More stats
  manager/forms.py
  manager/migrations/0024_auto_20210827_1310.py
  manager/models.py
  manager/templatetags/filters.py
  package-lock.json
  src/scss/_mixins.scss
  src/scss/components/_stats.scss
  src/scss/style.scss
  static/css/style.min.css
  templates/manager/campaign-stats.html
Labels: enhancement

#129 Removed clickable table rows
  src/js/script/global.js
  src/scss/_tables.scss
  static/css/style.min.css
  static/js/script.min.js
  templates/manager/campaign-list.html
  templates/manager/email-instances.html
  templates/manager/email-unsubscriptions.html
  templates/manager/emails.html
  templates/manager/instructions.html
  templates/manager/recipient-recipientattributes.html
  templates/manager/recipientgroup-recipients.html
  templates/manager/recipientgroup-update.html
  templates/manager/recipientgroups.html
  templates/manager/recipients.html
  templates/manager/settings.html
  templates/manager/subscription-category-list.html
Labels: enhancement

#130 Hotfixes for Stats
  manager/models.py
  manager/templatetags/filters.py
  manager/views.py
  templates/manager/campaign-stats.html
Labels: bug
